### ISSUE TITLE
trademark™ unicode in game title throws error

### ISSUE THREAD

**Issue by ghost** [jayme-github/steam_idle#3] opened 2015-11-17 14:24 UTC
While idling games with ™ (Unicode character 2122) in game title, I get this error:

```
Traceback (most recent call last):
  File "steam_idle_cli.py", line 158, in <module>
    main_idle(apps)
  File "steam_idle_cli.py", line 30, in main_idle
    p = IdleChild(app)
  File "/home/nick/.steam_idle/steam_idle/idle.py", line 18, in __init__
    self.name += '-[%s]' % str(self.app.name if self.app.name else self.app.appid)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 24: ordinal not in range(128)
```

**Comment by jayme-github** [comment] 2015-11-18 10:01
duplicate of issue #4

**Closed as completed by jayme-github** 2015-11-18 10:01 UTC
